pipeline {
    agent any
    tools {
      terraform 'Terraform'
    }
    stages {
        //stage('Git checkout') {
        //    steps {
        //         git 'https://github.com/leidychaconc/terraformGoogle'
        //    }
        //}
        stage('Terraform init') {
            steps {
                sh 'terraform init'
            }
        }
        stage('Terraform Apply') {
            steps {
                sh 'terraform apply -auto-approve'
            }
        }
    }
}
